input:
    input.go: |
        package structs

        // goverter:converter
        // goverter:useZeroValueOnPointerInconsistency 1 2
        type Converter interface {
            Convert(Input) Output
        }

        type Input struct { Name string }
        type Output struct { Name string }
error: |-
    error parsing 'goverter:useZeroValueOnPointerInconsistency' at
        @workdir/input.go:5:1
        github.com/emp1re/goverter-test/execution.Converter

    expected at most one value but got 2: []string{"1", "2"}
